# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  server_host: 0.0.0.0
  trusted_proxies:
    - 172.19.0.0/16  # Docker network for nginx proxy
    - 127.0.0.1
    - 100.64.0.0/10  # или точный IP Tailscale-пиринга


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

